[project]
name = "comfyui-multigpu"
description = "Experimental nodes for using multiple GPUs in a single ComfyUI workflow. Support for GGUF and other popular custom loaders. Example workflows for SDXL, FLUX, LTXVideo, and Hunyuan Video"
version = "1.0.1"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/pollockjj/ComfyUI-MultiGPU"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "pollockjj"
DisplayName = "ComfyUI-MultiGPU"
Icon = ""
